# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IWZjBO9Of1CdUsQmkc8hDLn-skrdGxt
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def set_name(self, name):
    self.name = name

  def show_name(self):
    print(self.name)

user = Human("山田太郎", 30)

print(user.name)
print(user.age)