# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IWZjBO9Of1CdUsQmkc8hDLn-skrdGxt
"""

def purchaced_cost(price, tax):
  tax_rate = tax / 100 + 1
  total = price * tax_rate

  print(f"{total}円です。")

purchaced_cost(1000, 10)