# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IWZjBO9Of1CdUsQmkc8hDLn-skrdGxt
"""

Area_trapezoid = (10 + 20) * 5 /2
print(str(Area_trapezoid) + 'cm²')