# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IWZjBO9Of1CdUsQmkc8hDLn-skrdGxt
"""

import random
ver = random.randint(1, 20)

if ver % 3 == 0 and ver % 5 != 0:
  print("Fizz")

elif ver % 5 ==0 and ver % 3 != 0:
  print("Buzz")

elif ver % 3 == 0 and ver % 5 == 0:
  print("FizzBuzz")

else:
  print(ver)