# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IWZjBO9Of1CdUsQmkc8hDLn-skrdGxt
"""

price1 = 100
price2 = 200

def total():
    tax = 1.1
    total_price = price1 + price2

    print (total_price * tax)

total()